### ISSUE TITLE
Erro ao "Duplicar plano" macro

### ISSUE THREAD

**Issue by HemersonGH** [forpdi/plataforma-for#26]
**Procedimento:**
Selecionar algum plano macro >> menu do Plano macro >> opção Duplicar plano.

**Erro:**

- [x] Após excluir toda a árvore do plano de meta, não é possível excluir o plano macro, é permitido excluir somente quando atualiza a página.

![image](https://user-images.githubusercontent.com/30694914/32224747-d4c21244-be29-11e7-93db-1de50e4a45b7.png)

![image](https://user-images.githubusercontent.com/30694914/32224769-e56b536c-be29-11e7-82a6-1cbb4597ebbe.png)

- [x] Quando é duplicado um plano macro que não tem Documento PDI, é criado a aba de documento PDI sem os itens da árvore. Também é mostrado um gif de loop infinito na janela dos documento.

![image](https://user-images.githubusercontent.com/30694914/32224901-5b1a23c2-be2a-11e7-82e1-43c5f1a832e9.png)

**Comment by isalvati** [comment]
Não consegui reproduzir a task 1

**Comment by Hemerson-GH** [comment]
Vou editar ela e detalhar mais.
