### ISSUE TITLE
[FORPDI] Arquivo .xml do plano de metas

### ISSUE THREAD

**Issue by DaniellPontes** [forpdi/plataforma-for#275]
Boa tarde!

O FORPDI está instalado no ambiente computacional da instituição em que trabalho, porém não há estrutura de plano de metas e não consigo encontrar o .xml para importar. 
Onde posso encontrá-lo?

**Comment by matheus0392** [comment]
o arquivo exemplo está no caminho:
[forpdi\backend-java\src\main\resources\structure-example.xml](https://github.com/forpdi/plataforma-for/blob/master/backend-java/src/main/resources/structure-example.xml)
