### ISSUE TITLE
Usuário admin sem permissões

### ISSUE THREAD

**Issue by santanarscs** [forpdi/plataforma-for#288]
Bom dia pessoal, fiz a instalação rápida do sistema, porém o usuário administrador veio sem as permissões, olhei as tabelas fpdi_role/role_permission/user_permission e todas elas estão vazias, como posso resolver isso? foi um erro na instalação ?

**Comment by phppa** [comment]
Bom dia!

Também tive problemas com isso.

No meu caso resolveu quando eu vinculei o administrador com a instituição:

INSERT INTO fpdi_company_user (accessLevel, blocked, notificationSetting, user_id, company_id) VALUES (100, false, 1, 1, 1);

**Comment by santanarscs** [comment]
Bom dia meu amigo, fiz esse procedimento e nao funcionou, mas estava vendo um video da ferramenta e vi que tinha q criar uma instituição e registrar o dominio válido do servidor, ai apareceu as opções para manter usuário
