### ISSUE TITLE
README.md - Links quebrados: Documentos e Capacitação

### ISSUE THREAD

**Issue by mgrb** [forpdi/plataforma-for#293]
Os seguintes links estão quebrados:

- Diagrama Entidade-Relacionamento ForPDI
- Diagrama Entidade-Relacionamento ForRisco
- Diagrama Entidade-Relacionamento ForPDI + ForRisco
- Dicionário de Dados ForPDI
- Dicionário de Dados ForRisco
- Dicionário de Dados ForPDI + ForRisco
- Documentação do Sistema (ForPDI)
- Documentação da Interface (ForPDI)
- Manual ForRisco

**Comment by michellino** [comment]
Os links foram corrigidos
