### ISSUE TITLE
Erro no build forpdi-frontend

### ISSUE THREAD

**Issue by tcm-sp** [forpdi/plataforma-for#297]
Ao executar o `docker-compose up` ocorre o erro abaixo:
```
Building forpdi-frontend
Step 1/14 : FROM node:10-stretch AS build
 ---> ea119cebc1c3
Step 2/14 : RUN npm i -g yarn node-gyp
 ---> Running in 994dd0f4b759
/usr/local/bin/node-gyp -> /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js
npm ERR! code EEXIST
npm ERR! syscall symlink
npm ERR! path ../lib/node_modules/yarn/bin/yarn.js
npm ERR! dest /usr/local/bin/yarn
npm ERR! errno -17
npm ERR! EEXIST: file already exists, symlink '../lib/node_modules/yarn/bin/yarn.js' -> '/usr/local/bin/yarn'
npm ERR! File exists: /usr/local/bin/yarn
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-13T20_23_19_722Z-debug.log
ERROR: Service 'forpdi-frontend' failed to build: The command '/bin/sh -c npm i -g yarn node-gyp' returned a non-zero code: 239
```
O `docker-compose up` para o mysql e o platfor-backend executaram sem erros.

Alguém já passou por este problema e pode nos ajudar?

Grato

**Comment by arthurd2** [comment]
Tentou recriar tudo?
`docker-compose up --force-recreate --build`

**Comment by tcm-sp** [comment]
Obrigado pela resposta arthrd2!

Tentei recriar tudo usando `docker-compose up --force-recreate --build` mas infelizmente continuou ocorrendo o mesmo erro.

Como no próprio erro continha a sugestão: 
```
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.
```
eu alterei o arquivo Dockerfile da pasta front-end e substituí o `RUN npm i -g yarn node-gyp` pelo `RUN npm i --force -g yarn node-gyp` e o build prosseguiu.

Contudo, ao executar `RUN NODE_ENV=production yarn build:docker` ocorreu o erro:
```
RUN NODE_ENV=production yarn build:docker
 ---> Running in 9a895059109e
yarn run v1.21.1
$ webpack-cli --config webpack.production.config.js -p
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
Killed
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 137.
ERROR: Service 'forpdi-frontend' failed to build: The command '/bin/sh -c NODE_ENV=production yarn build:docker' returned a non-zero code: 137
```
Verifiquei se o erro era ocasionado por insuficiência de memória por causa do código 137, mas ao verificar o container com o `docker inspect`  ele apresenta:
```
"State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 137,
            "Error": "",
            "StartedAt": "2020-01-14T16:57:19.6650642Z",
            "FinishedAt": "2020-01-14T08:59:49.4667224-08:00"
```
como "OOMKilled" está falso, acho que o kill foi ocasionado por outro motivo...

Será que alguém já se deparou com este problema e pode ajudar?

Grato!!

**Comment by tcm-sp** [comment]
Infelizmente não consegui fazer o build no ambiente de produção por causa do erro.

A solução que encontrei foi fazer o build em outro ambiente, salvar a imagem em um arquivo .tar e importar a imagem do forpdi-frontend no servidor de produção.

**Comment by arthurd2** [comment]
Salve Salve! Acredito que ja tenha arrumado isto.
Fiz um MergeRequest a mais de mes mas o pessoal nao aceitou ainda. :/

**Comment by cristianofatec** [comment]
Alguém já solucionou?
Passo pelo mesmo problema!
Poderiam postar a solução aqui?
