### ISSUE TITLE
falha ao subir o docker-compose

### ISSUE THREAD

**Issue by cristianofatec** [forpdi/plataforma-for#298]
Aparece o seguinte erro: (em vermelho)

 ---> Running in 8146fc344ec7
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
/usr/local/bin/node-gyp -> /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js
npm ERR! code EEXIST
npm ERR! syscall symlink
npm ERR! path ../lib/node_modules/yarn/bin/yarn.js
npm ERR! dest /usr/local/bin/yarn
npm ERR! errno -17
npm ERR! EEXIST: file already exists, symlink '../lib/node_modules/yarn/bin/yarn.js' -> '/usr/local/bin/yarn'
npm ERR! File exists: /usr/local/bin/yarn
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-04T14_29_48_174Z-debug.log
ERROR: Service 'forpdi-frontend' failed to build: The command '/bin/sh -c npm i -g yarn node-gyp' returned a non-zero code: 239

**Comment by arthurd2** [comment]
Arrumei o Dockerfile do front-end, pode puxar do meu fork se quiser. Ainda estou aguardando aceitarem o PR.

**Comment by cristianofatec** [comment]
A porta padrão para acessar no seu fork é a 8181, correto?

**Comment by cristianofatec** [comment]
Deu certo aqui, valeu!
