### ISSUE TITLE
Não envia e-mails

### ISSUE THREAD

**Issue by cristianofatec** [forpdi/plataforma-for#299]
Ao convidar um usuário, o mesmo não está recebendo o e-mail com o link.
Qual arquivo de configuração devo editar?

Ps. Usei a instalação com o docker-compose.yml

Segue o conteúdo do arquivo yml:

version: "3.5"

services:
        forpdi-database:
                image: mysql:5.7
                environment:
                        MYSQL_ROOT_PASSWORD: docker12345
                        MYSQL_DATABASE: plataformafor
        forpdi-backend:
                build: ./backend-java
                image: platfor-backend
                depends_on:
                        - forpdi-database
                ports:
                        - 8009:8009
                        - 8080:8080
        forpdi-frontend:
                build: ./frontend-web
                image: platfor-front
                depends_on:
                        - forpdi-backend
                ports:
                        - 80:80

**Comment by arthurd2** [comment]
Acredito que esteja no docker.dev.properties : https://github.com/forpdi/plataforma-for/blob/master/backend-java/conf/docker.dev.properties

**Comment by cristianofatec** [comment]
Configurei este arquivo, mas continua não enviando.. Continua tentando enviar pela porta 25, sendo que eu configurei a porta 587. A mensagem de erro que aparece:

 Caused by: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: localhost, 25; timeout 60000;

**Comment by cristianofatec** [comment]
Não é o caso de configurar o Dockerfile? As configurações de ENV

**Comment by arthurd2** [comment]
Depois de mudar o docker.dev.properties nao esqueça de remover o container e a imagem, para ele recompilar o projeto.

Sobre passar as confs pro Dockerfile, sim, seria o ideal, mas como os desenvolvedores não estão aceitando os PRs, não faz sentido...

**Comment by cristianofatec** [comment]
Valeu Arthur, funcionou!
