### ISSUE TITLE
Instalação Plataforma-for no Windows 10

### ISSUE THREAD

**Issue by AdrianoUFSB** [forpdi/plataforma-for#302]
Olá!

Estou tentando instalar o ForPdi no windows 10 (notebook), tentei utilizar um tutorial elaborado pelo Vitor Muniz, mas tive alguns problemas e não consegui gerar. Existe algum outro tutorial que eu possa utilizar.

Sou da UFSB mas trabalho na DIRPLAN e queria utilizar a aplicação pois no futuro iremos utilizá-la.

Agradeço desde já.

Segue tutorial que utilizei.
[Tutorial_Instalacao_Plataforma_For_Windows-1.pdf](https://github.com/forpdi/plataforma-for/files/4659226/Tutorial_Instalacao_Plataforma_For_Windows-1.pdf)

**Comment by michellino** [comment]
Qual problema você teve na instalação ?

**Comment by AdrianoUFSB** [comment]
Já instalei com sucesso michellino, grato!
O problema que tive foi referente a versões e algumas dicas que não constavam no documento.
