### ISSUE TITLE
Documentação fora do ar

### ISSUE THREAD

**Issue by ArthurPieri** [forpdi/plataforma-for#318]
Os links utilizados no README.MD do projeto estão com links quebrados, sendo os links que não funcionam: 

Diagrama Entidade-Relacionamento ForPDI
Diagrama Entidade-Relacionamento ForRisco
Diagrama Entidade-Relacionamento ForPDI + ForRisco
Dicionário de Dados ForPDI
Dicionário de Dados ForRisco
Dicionário de Dados ForPDI + ForRisco
Documentação do Sistema (ForPDI)
Documentação da Interface (ForPDI)
Manual ForPDI
Manual ForRisco

**Comment by michellino** [comment]
A documentação foi atualizada
