### ISSUE TITLE
Problema para importar estrutura de plano de metas (commit 78447dc)

### ISSUE THREAD

**Issue by wgdantas** [forpdi/plataforma-for#338]
Prezados, aparentemente, o commit 78447dc76a4b853e08e8d59f641c8cd152f31b32 "quebrou" a funcionalidade de importação de plano de metas. Com a mudança desse commit, a barra de progresso do modal vai até o fim e para, e o carregamento do arquivo XML com a estrutura do plano de metas não é finalizado.

Poderiam verificar isso, por favor?

**Comment by AdrianoUFSB** [comment]
Wdgantas, obrigado pela postagem referente ao problema #322, porém o MEC/RNP assumiram o  FORPDI e talvez eles estejam lançando uma versão agora no final de junho com correções e melhorias.

Grato.

**Comment by wgdantas** [comment]
@AdrianoUFSB , o link para o Projeto ForPDI permanecerá o mesmo?

**Comment by wgdantas** [comment]
Em relação ao problema lançado aqui, rastreei os seguintes arquivos do Frontend ForPDI atingidos pela mudança do método `uploadFile` em **frontend-web/jsx/core/widget/Modal.jsx**:

    frontend-web/jsx/MainMenu.jsx
    frontend-web/jsx/planning/view/plan/PlanMacroEdit.jsx
    frontend-web/jsx/planning/view/structure/StructureList.jsx
    frontend-web/jsx/vendor/FPDIRichText.jsx

Em todos esses casos, alterei as chamadas a `uploadFile`, de:

    uploadFile(...

Para:

    uploadFile({},...

No caso da importação de estrutura de plano de metas, funcionou.

**Comment by wgdantas** [comment]
Na interface do ForRisco, ocorre o mesmo problema. Apliquei a [mesma solução antes relatada](https://github.com/forpdi/plataforma-for/issues/338#issuecomment-862380469). 

Arquivos do ForRisco atingidos pelo problema:

```
jsx_forrisco/planning/view/item/FieldItemInput.jsx
jsx_forrisco/planning/view/unit/item/UnitProcess.jsx
jsx_forrisco/planning/widget/planrisk/item/PlanRiskItemField.jsx
jsx_forrisco/planning/widget/unit/item/UnitItemField.jsx
```
