### ISSUE TITLE
Erro ao tentar gerar relatório

### ISSUE THREAD

**Issue by lcnogueira** [forpdi/plataforma-for#39]
Estou tendo um erro ao clicar no link _Gerar relatório_ dentro do plano de metas. Quando clico no link, ele me retorna tipo um json. Segue imagem do caminho que estou percorrendo:
![forpdi1](https://user-images.githubusercontent.com/12154623/32963879-22401924-cbb0-11e7-9998-6db7d6465a16.png)

Resultado retornado:
![forpdi2](https://user-images.githubusercontent.com/12154623/32963907-3dbb243c-cbb0-11e7-8c10-dcbd59345159.png)

Teria alguma ideia do que pode estar ocorrendo? Falta de cadastro de alguma info ou algo assim?

**Comment by Hemerson-GH** [comment]
Olá @lcnogueira, sou da equipe de desenvolvimento do FORPDI e tentei reproduzir esse erro, porém não obtive exito, poderia descrever mais passos de como isso ocorreu ?

**Comment by lcnogueira** [comment]
Oi @Hemerson-GH , obrigado pelo retorno. Fizemos o seguinte: inserimos um Plano de Metas, depois cadastramos o Eixo temático, depois o objetivo e depois a meta. Ao entrar em cada eixo temático, objetivo ou meta ocorre a seguinte mensagem de erro no sistema: **_Ocorreu um erro insperado: Could Not Extract ResultSet._** Da mesma forma, quando tentamos gerar algum relatório deles, ocorre essa mensagem em uma nova janela, conforme coloquei na imagem na abertura dessa issue.

**Comment by Hemerson-GH** [comment]
Olá @lcnogueira eu reproduzi esses passos nos ambientes local e mirror, porém esse erro não aconteceu em nenhum dos dois, teria como você criar um usuário e compartilhar os dados dele para eu poder tentar reproduzir esse erro ?

**Comment by lcnogueira** [comment]
Oi @Sergio-Berbert. Eu não encontrei não. Devido às outras demandas e por uma questão de prioridade, eu não fiz uma busca minunciosa pela solução.

**Comment by Sergio-Berbert** [comment]
Grato, amigo! Então você continua com o problema?

**Comment by lcnogueira** [comment]
Sim, @Sergio-Berbert. Acabei de simular o fluxo na ferramenta e o erro persiste.

**Comment by Sergio-Berbert** [comment]
Grato, @lcnogueira !

**Comment by Sergio-Berbert** [comment]
Boa tarde, @HemersonGH ! Alguma possibilidade de solução para esse problema?

**Comment by renatorroliveira** [comment]
É preciso uma revisão completa da geração do relatório após a inclusão do ForRisco e para correção de bugs históricos. Acompanhar em #281
