### ISSUE TITLE
Erro ao exportar Documento do PDI

### ISSUE THREAD

**Issue by HemersonGH** [forpdi/plataforma-for#52]
**Procedimento:**
Exportar Documento do PDI.

**Erro:**
Ao invés de gerar o pdf, é exibido a seguinte mensagem de erro:

![whatsapp image 2018-01-17 at 09 44 17](https://user-images.githubusercontent.com/30694914/35106287-f9fe4488-fc54-11e7-8c73-b9c3d8b68cd0.jpeg)

**Comment by gustavomelo10** [comment]
O erro apenas acontece quando há algum plano de metas vinculado a alguma seção do documento.

**Comment by andre-ls-freitas** [comment]
E não tem como exportar o plano de metas para compor o documento do PDI?

**Comment by renatorroliveira** [comment]
@TheKipmaster Você chegou a corrigir este problema?

**Comment by renatorroliveira** [comment]
Acompanhar em #281, será necessária uma revisão completa da exportação de relatório.
