### ISSUE TITLE
"Could not extract ResultSet"

### ISSUE THREAD

**Issue by Sergio-Berbert** [forpdi/plataforma-for#69]
Ao navegar pelos Planos de Metas tem aparecido a mensagem "Could not extract ResultSet" , conforme Print Screen anexado. O que isso significa?

![could not extract resultset](https://user-images.githubusercontent.com/40361233/41553979-c4859a64-7309-11e8-9542-c2dd9d587bbc.JPG)

**Comment by renatorroliveira** [comment]
Isso é uma falha em realizar alguma consulta ao banco de dados.
Acabamos de identificar algumas referências estáticas ao nome do banco de dados, no caso `forpdi_db`. Você alterou o nome da base de dados onde está executando o ForPDI?

**Comment by renatorroliveira** [comment]
Corrigido pela inclusão do nome do banco de dados no arquivo de properties.
