### ISSUE TITLE
Não aparece objetivo cadastrado no eixo temático

### ISSUE THREAD

**Issue by Sergio-Berbert** [forpdi/plataforma-for#71]
Ao abrir um eixo temático, aparece a mensagem de erro "Coud not extract ResultSet" e não aparecem os objetivos já cadastrados no mesmo

![nao aparecem objetivos cadastrados no eixo tematico](https://user-images.githubusercontent.com/40361233/41553525-65462c18-7308-11e8-9928-2c466cbd4413.JPG)

**Comment by renatorroliveira** [comment]
Corrigido pela inclusão do nome do banco de dados no arquivo de properties.
